name: Publicar pacote
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Instalar dependências
        run: npm ci

      - name: Token do npm
        run: echo ${{secrets.NPM_TOKEN}}

      - name: Publicar o pacote
        run: npm run pub
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
